//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanData
{
    using System;
    
    public partial class GET_SPECIAL_BIDS_Result1
    {
        public int idSpecialBid { get; set; }
        public string idLocalization { get; set; }
        public string idMaterial { get; set; }
        public int Quantity { get; set; }
        public bool Active { get; set; }
        public string Upload_User { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public string Comments { get; set; }
        public string Lean_Application { get; set; }
        public string Line { get; set; }
    }
}
